project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-N8JCQBV6PD"
  title: "Mark Buckner"
  site-url: "https://markabuckner.com"
  navbar:
    left:
      - href: about.qmd
        text: about
      - href: pubs.qmd
        text: Publications
      - href: outreach.qmd
        text: Outreach
      # - href: cv.qmd
      #   text: CV
      - href: projects.qmd
        text: Research
        
    right:
      # - href: blog/blog.qmd
      #   text: Cartograph(bee)
      - href: dsw_poster.qmd
        text: Desert Bees Poster
      - icon: envelope
        href: mailto:mab677@cornell.edu
      - icon: github
        href: https://github.com/bcknr
      - icon: linkedin
        href: https://www.linkedin.com/in/bucknerm
        
  page-footer:
    left: "\u00A9 2023-2024, Mark Buckner"
    right: 
      - icon: github
        href: https://github.com/bcknr/bcknr

format:
  html:
    theme: 
      light: lux
      dark: [lux, theme-dark.scss]
    css: styles.css
    toc: true
    grid:
      sidebar-width: 100px
      body-width: 1050px
      margin-width: 300px



